version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: admin
      POSTGRES_DB: moods-dev
    ports:
      - 5432:5432
