version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: moodsdb
    ports:
      - 5432:5432
  # web:
  #   build: .
  #   volumes: .:/moods
  #   command: cargo run
  #   depends_on:
  #     - db
